[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "git"]

[phases.install]
cmds = ["python -m pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"